### ISSUE TITLE
Create function to insert to MongoDB in an easier way

### ISSUE THREAD

**Issue by ed-henrique** [ed-henrique/yasse#15]
What we need is a function that does all we are doing related to MongoDB [here](https://github.com/ed-henrique/yasse/blob/dev/backend/src/crawlers/anime/goyabu_crawler/src/main.ts).

In short, the function must:

- Connect to MongoClient
- use insertMany() to insert a list of documents at once
- Close the client

**Comment by zainbinfurqan** [comment]
Can you please elaborate more? and can you assign it to me please.

**Comment by ed-henrique** [comment]
Sure thing. What we need is a function that does all we are doing related to MongoDB [here](https://github.com/ed-henrique/yasse/blob/dev/backend/src/crawlers/anime/goyabu_crawler/src/main.ts).

In short, the function must:

- Connect to MongoClient
- use insertMany() to insert a list of documents at once
- Close the client

**Comment by ed-henrique** [comment]
I created the function (refer to [0a22d39](https://github.com/ed-henrique/yasse/commit/0a22d395f7b4186d51aa8204b98ffa120b8c2158) ), but it still needs to be applied to all existing crawlers, so there's still work to do.

**Comment by ed-henrique** [comment]
Done in ed-henrique@962494c.
